
name: CICD-docker-image
run-name: "${{ github.workflow }}-${{ github.run_id }}.${{ github.run_attempt }}"

on:
    workflow_dispatch:
        inputs:
            IMAGE_TAG:
                description: "Image version"
                required: false
                default: "latest"

env:
    IMAGE_NAME: dt-ubu
    DOCKER_REPO: mfurones/devopstool

jobs:
    j_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
      
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                file: docker/ct-ubuntu.dockerfile
                context: .
                push: true
                tags: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.IMAGE_TAG }}
